## -----------------------------------------------------------------------------
## GitLab CI configuration file
##
## @author     Lars Thoms <lars@thoms.io>
## @date       2025-01-09
## -----------------------------------------------------------------------------

---
## -----------------------------------------------------------------------------
## Configuration
## -----------------------------------------------------------------------------

include:
  - project: dl.min/technik/git-templates
    file:
      - /GitLab CI/Python.test.gitlab-ci.yml
...
